on: [push]

jobs:
  test-checksum:
    name: Test checksum action on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: Huy-Ngo/gha-sha@v1.0.5
        with:
          glob: 'LICENSE'
